# Generated by Django 5.1.1 on 2024-09-09 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_endpoint_mlalgorithm_mlalgorithmstatus_mlrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="textsample",
            name="mlrequest_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.mlrequest",
            ),
        ),
    ]
