# Generated by Django 5.1.1 on 2024-09-09 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_textsample_mlrequest_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="textsample",
            old_name="mlrequest_id",
            new_name="mlrequest",
        ),
        migrations.AddField(
            model_name="textsample",
            name="endpoint_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
